import json
from typing import Any, Dict, List

def parse_gemini_chat_json(content: str) -> List[Dict[str, Any]]:
    """
    Parses a JSON string generated by gemini-cli's chat share feature.
    Returns a list of dictionaries, where each dictionary represents a message turn.
    """
    try:
        data = json.loads(content)
        if not isinstance(data, list):
            raise ValueError("Expected a list of messages at the root of the JSON file.")
        
        parsed_messages = []
        for turn in data:
            role = turn.get("role")
            parts = turn.get("parts", [])
            
            # Initialize a message turn dictionary
            message_data: Dict[str, Any] = {
                "role": role,
                "text": "",
                "function_calls": [],
                "function_responses": [],
                "thought_signatures": []
            }
            
            text_parts = []
            for part in parts:
                if "text" in part:
                    text_parts.append(part["text"])
                
                if "thoughtSignature" in part:
                    message_data["thought_signatures"].append(part["thoughtSignature"])
                
                if "functionCall" in part:
                    message_data["function_calls"].append(part["functionCall"])
                
                if "functionResponse" in part:
                    message_data["function_responses"].append(part["functionResponse"])
            
            message_data["text"] = "\n".join(text_parts).strip()
            
            # Clean up empty fields to keep the dicts concise
            final_data = {k: v for k, v in message_data.items() if v}
            # Always keep role and text (even if empty) for consistency
            final_data["role"] = role
            final_data["text"] = message_data["text"]
            
            parsed_messages.append(final_data)
            
        return parsed_messages
    except json.JSONDecodeError as e:
        raise ValueError(f"Failed to parse JSON content: {e}")

if __name__ == "__main__":
    import sys
    from pathlib import Path
    
    file_path = "session-a.json"
    if len(sys.argv) > 1:
        file_path = sys.argv[1]
        
    try:
        content = Path(file_path).read_text()
        messages = parse_gemini_chat_json(content)
        print(f"Parsed {len(messages)} turns from {file_path}")
        
        # Display the first few turns as a sample
        for i, msg in enumerate(messages[:3]):
            print(f"\n--- Turn {i+1} ({msg['role']}) ---")
            if msg['text']:
                preview = msg['text'][:100].replace('\n', ' ')
                print(f"Text: {preview}...")
            if "function_calls" in msg:
                print(f"Calls: {[fc['name'] for fc in msg['function_calls']]}")
            if "function_responses" in msg:
                print(f"Responses: {[fr['name'] for fr in msg['function_responses']]}")
                
    except FileNotFoundError:
        print(f"Error: {file_path} not found.")
    except Exception as e:
        print(f"An error occurred: {e}")
